name: Gamer Frontend Pipeline

on:
  push:
    branches: [ master ]


jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Install the needed dependencies
    - name: Install dependencies
      run: npm ci

    # Build the application
    - name: Build
      run: npm run build --prod

    # Testing the application
    - name: Test
      run: npm run ci:test
    
    # Build and deploy the application to Docker Hub
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: kranky23/gamerfrontend
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: kranky23
        password: ${{ secrets.DOCKER_PWD }}

    # - name: Run unit tests
    #   run: npm run ci:test