name: Gamer Frontend Pipeline

on:
  push:
    branches: [ master ]


jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t kranky23/gamerfrontend:latest .
    - name: Docker login
      run: docker login ---username kranky23 --password {{secrets.DOCKER_PWD}}
    - name: Docker push
      run: docker push kranky23/gamerfrontend
