name: Gamer Frontend Pipeline

on:
  push:
    branches: [ master ]


jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build & push Docker image
      with:
        image: kranky23/gamerfrontend
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ kranky23 }}
        password: ${{ secrets.DOCKER_PWD }}
