name: Gamer Frontend Pipeline

on:
  push:
    branches: [ master ]


jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: kranky23/gamerfrontend
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: kranky23
        password: ${{ secrets.DOCKER_PWD }}

    - name: Run unit tests
      run: npm test
